#ifndef ENV_H
#define ENV_H
#define ROBOT_VERSION_STRING "CHANGE ME TO USER:COMPUTER"

//#define ENABLE_DRIVETRAIN
//#define ENABLE_CLIMBER
//#define ENABLE_LAUNCHER
//#define ENABLE_VISION

#endif // ENV_H
